from fastapi import APIRouter
from fastapi.responses import FileResponse

from app.export.export_service import (
    export_json,
    export_pdf
)

from app.services.analysis_storage_service import (
    get_text_analysis,
    get_vitals_analysis,
    get_report_analysis
)

from app.services.doctor_visit_service import (
    get_doctor_visit_data,
)

router = APIRouter(
    prefix="/export",
    tags=["Export"]
)


# =========================
# TEXT ANALYSIS EXPORT
# =========================

@router.post("/text/pdf")
async def export_text_pdf():

    analysis_data = get_text_analysis()

    if not analysis_data:

        return {
            "error":
            "No text analysis available yet"
        }

    filepath = export_pdf(
        analysis_data,
        "text_analysis_report.pdf"
    )

    return FileResponse(
        path=filepath,
        filename="text_analysis_report.pdf",
        media_type="application/pdf"
    )


@router.post("/text/json")
async def export_text_json():

    analysis_data = get_text_analysis()

    if not analysis_data:

        return {
            "error":
            "No text analysis available yet"
        }

    filepath = export_json(
        analysis_data,
        "text_analysis_report.json"
    )

    return FileResponse(
        path=filepath,
        filename="text_analysis_report.json",
        media_type="application/json"
    )


# =========================
# REPORT OCR EXPORT
# =========================

@router.post("/report/pdf")
async def export_report_pdf():

    analysis_data = get_report_analysis()

    if not analysis_data:

        return {
            "error":
            "No OCR report analysis available yet"
        }

    filepath = export_pdf(
        analysis_data,
        "ocr_report.pdf"
    )

    return FileResponse(
        path=filepath,
        filename="ocr_report.pdf",
        media_type="application/pdf"
    )


@router.post("/report/json")
async def export_report_json():

    analysis_data = get_report_analysis()

    if not analysis_data:

        return {
            "error":
            "No OCR report analysis available yet"
        }

    filepath = export_json(
        analysis_data,
        "ocr_report.json"
    )

    return FileResponse(
        path=filepath,
        filename="ocr_report.json",
        media_type="application/json"
    )


# =========================
# VITALS EXPORT
# =========================

@router.post("/vitals/pdf")
async def export_vitals_pdf():

    analysis_data = get_vitals_analysis()

    if not analysis_data:

        return {
            "error":
            "No vitals analysis available yet"
        }

    filepath = export_pdf(
        analysis_data,
        "vitals_report.pdf"
    )

    return FileResponse(
        path=filepath,
        filename="vitals_report.pdf",
        media_type="application/pdf"
    )


@router.post("/doctor-visit-summary/pdf")
async def export_doctor_visit_summary_pdf(user_id: str = "demo_user"):

    record = get_doctor_visit_data(user_id)

    if not record:
        return {
            "error": "No doctor visit preparation found yet"
        }

    summary = record.get("summary", {}) or {}
    summary_text = summary.get("summaryText") if isinstance(summary, dict) else str(summary)
    summary_text = summary_text or "No doctor visit summary available."

    extra_lines = []
    medications = record.get("medications", [])
    symptoms = record.get("symptoms", [])

    if medications:
        extra_lines.append("Medications:")
        for med in medications:
            med_name = med.get("name", "Unknown medication")
            med_dosage = med.get("dosage", "No dosage provided")
            med_reason = med.get("reason", "No reason provided")
            extra_lines.append(f"- {med_name} | {med_dosage} | {med_reason}")
        extra_lines.append("")

    if symptoms:
        extra_lines.append("Symptom timeline:")
        for sym in symptoms:
            date = sym.get("date", "Unknown date")
            location = sym.get("location", "General discomfort")
            intensity = sym.get("intensity", "N/A")
            triggers = sym.get("triggers", "No trigger listed")
            notes = sym.get("notes", "No notes provided")
            extra_lines.append(
                f"- {date}: {location} | intensity {intensity}/10 | triggers: {triggers} | notes: {notes}"
            )
        extra_lines.append("")

    export_data = {
        "summary": summary_text + ("\n\n" + "\n".join(extra_lines) if extra_lines else ""),
        "doctor_prep": {
            "questions": summary.get("questions", []) if isinstance(summary, dict) else []
        },
        "disclaimer": "Generated by CareInCode doctor visit preparer.",
    }

    filepath = export_pdf(
        export_data,
        "doctor_visit_summary.pdf"
    )

    return FileResponse(
        path=filepath,
        filename="doctor_visit_summary.pdf",
        media_type="application/pdf"
    )


@router.post("/vitals/json")
async def export_vitals_json():

    analysis_data = get_vitals_analysis()

    if not analysis_data:

        return {
            "error":
            "No vitals analysis available yet"
        }

    filepath = export_json(
        analysis_data,
        "vitals_report.json"
    )

    return FileResponse(
        path=filepath,
        filename="vitals_report.json",
        media_type="application/json"
    )